### ISSUE TITLE
Weird colors

### ISSUE THREAD

**Issue by littke** [groenewege/vim-less#34] opened 2013-10-31 09:48 UTC
Getting wrong colors on 'font-size', 'border', 'color', etc.

Using vim-less, vim-css3-syntax, vim-css-color, MacVim 72, OS X Mavericks.

https://www.dropbox.com/s/5ikoeclnq5ixy9b/Screenshot%202013-10-31%2010.47.58.png

**Comment by dhruvasagar** [comment] 2015-06-05 13:58
Hi, I had a look into this, this seems to be stemming from native css syntax which less plugin includes. To me it looks like a `feature` rather than a `bug` because from the looks of it css plugin is trying to differentiate between css attributes.

**Comment by juanghurtado** [comment] 2015-06-08 06:14
Well, it may be a "feature" as you say. But… what is the css plugin trying
to differentiate? I mean… according to the screenshot I sent, margin and
padding attributes are being highlighted in a different way. Why is it so?
The same with the different "font" attributes.

What is the criteria for this?

2015-06-05 15:58 GMT+02:00 Dhruva Sagar <notifications@github.com>:

> Hi, I had a look into this, this seems to be stemming from native css
> syntax which less plugin includes. To me it looks like a feature rather
> than a bug because from the looks of it css plugin is trying to
> differentiate between css attributes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groenewege/vim-less/issues/34#issuecomment-109302287>.
>



-- 
Juan G. Hurtado
juan.g.hurtado@gmail.com

**Comment by dhruvasagar** [comment] 2015-06-08 07:29
@juanghurtado Can you give me a more recent screenshot ? Also which version of vim are you using ?

All `font-*` should be highlighted same, since they correspond to `cssFontProp` highlight group.
Similarly `border-*` ones are `cssBorderProp`, `margin` is `cssBoxProp`, `padding` is `cssUiProp`.

Like I said, css syntax definition is trying to be very granular and tries to make similar styles look similar by making them belong to the same highlight groups.

How they look eventually is still subject to your colorscheme, and also possibly affected by any additional css plugins that you might be using.

**Comment by dhruvasagar** [comment] 2015-06-29 11:16
Since this isn't directly related / caused by vim-less, I am going to close this for now.

**Closed by dhruvasagar** 2015-06-29 11:16 UTC
