### ISSUE TITLE
NameError for undefined variable even though variable defined in imported file

### ISSUE THREAD

**Issue by jsdalton** [groenewege/vim-less#14] opened 2012-04-02 14:31 UTC
vim-less raises a NameError when a variable is undefined. However, it ignores the fact that a variable might be defined somewhere else in an imported file.

**Comment by xavierartot** [comment] 2015-02-17 21:40
Same for me ?

**Comment by WellerQu** [comment] 2016-10-18 05:43
@jsdalton eh... I have the same problem, Did you resolve it? Thanks

**Comment by dhruvasagar** [comment] 2019-06-21 19:02
I am unable to reproduce this, closing for now.

**Closed by dhruvasagar** 2019-06-21 19:02 UTC
